name: Release

on:
  workflow_run:
    workflows: ['Snyk Security Check']
    branches: [main, beta]
    types:
      - completed

# on:
#   push:
#     branches: [main, beta]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    permissions:
        packages: write
        contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup Node.js
      uses: actions/setup-node@v2
      # with:
      #   node-version: 'lts/*'
      with:
        node-version: 20.x
    - name: Create .npmrc file
      run: |
        echo 'registry=https://registry.npmjs.org/' >> .npmrc
        echo '@uzenith360:registry=https://npm.pkg.github.com/' >> .npmrc
        echo '//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN  }}' >> .npmrc
    - name: Install dependencies
      run: npx ci
      # run: npm ci
    - name: Install semantic-release extra plugins
      run: npm install --save-dev @semantic-release/changelog @semantic-release/git
    - name: Lint
      run: npm run lint-fix --if-present
    - name: Test
      run: npm test -- --watch=false --browsers=ChromeHeadless
    - name: Build
      run: npm run build 
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npx semantic-release